import { apiClient } from './apiClient';

/**
 * Utility to convert base64url string to Uint8Array for PushManager applicationServerKey.
 */
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export const pushNotificationService = {
  /**
   * Check if the browser supports Service Workers and Web Push notifications.
   */
  isPushSupported(): boolean {
    return (
      typeof window !== 'undefined' &&
      'serviceWorker' in navigator &&
      'PushManager' in window &&
      'Notification' in window
    );
  },

  /**
   * Get current notification permission state.
   */
  getPermissionState(): NotificationPermission | 'unsupported' {
    if (!this.isPushSupported()) return 'unsupported';
    return Notification.permission;
  },

  /**
   * Register the Service Worker.
   */
  async registerServiceWorker(): Promise<ServiceWorkerRegistration | null> {
    if (!this.isPushSupported()) return null;
    try {
      const registration = await navigator.serviceWorker.register('/sw.js', {
        scope: '/',
      });
      return registration;
    } catch (err) {
      console.error('Service Worker registration failed:', err);
      return null;
    }
  },

  /**
   * Fetch VAPID public key from backend API.
   */
  async getVapidPublicKey(): Promise<string> {
    const res = await apiClient.get<{ vapid_public_key: string }>('/notifications/vapid-public-key');
    return res.data.vapid_public_key;
  },

  /**
   * Request permission and subscribe browser to Web Push notifications.
   */
  async subscribe(): Promise<boolean> {
    if (!this.isPushSupported()) return false;

    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      return false;
    }

    const registration = await this.registerServiceWorker();
    if (!registration) return false;

    const vapidPublicKey = await this.getVapidPublicKey();
    const convertedKey = urlBase64ToUint8Array(vapidPublicKey);

    let subscription = await registration.pushManager.getSubscription();
    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedKey.buffer as ArrayBuffer,
      });
    }

    const subJson = subscription.toJSON();
    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      throw new Error('Malformed push subscription object generated by browser.');
    }

    await apiClient.post('/notifications/push-subscription', {
      endpoint: subJson.endpoint,
      p256dh_key: subJson.keys.p256dh,
      auth_key: subJson.keys.auth,
      user_agent: navigator.userAgent.slice(0, 500),
    });

    return true;
  },

  /**
   * Unsubscribe browser locally and notify backend API.
   */
  async unsubscribe(): Promise<boolean> {
    if (!this.isPushSupported()) return false;

    const registration = await navigator.serviceWorker.getRegistration();
    if (!registration) return false;

    const subscription = await registration.pushManager.getSubscription();
    if (!subscription) return false;

    const endpoint = subscription.endpoint;
    await apiClient.delete('/notifications/push-subscription', {
      data: { endpoint },
    });

    await subscription.unsubscribe();
    return true;
  },

  /**
   * Query subscription status from backend.
   */
  async getStatus(): Promise<{ has_active_subscription: boolean; active_count: number }> {
    const res = await apiClient.get<{ has_active_subscription: boolean; active_count: number }>(
      '/notifications/push-subscription/status'
    );
    return res.data;
  },
};
