"""Add placement stages and assignments

Revision ID: ad9f7c530c09
Revises: 0003
Create Date: 2026-09-09 20:43:01.250106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9f7c530c09'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage_type', sa.String(length=50), nullable=False),
    sa.Column('sequence_order', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_or_link', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage_type IN ('APTITUDE', 'TECHNICAL', 'HR', 'GD')", name='chk_stage_type'),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'sequence_order', name='uq_stage_drive_sequence')
    )
    op.create_index(op.f('ix_placement_stages_drive_id'), 'placement_stages', ['drive_id'], unique=False)
    op.create_index(op.f('ix_placement_stages_sequence_order'), 'placement_stages', ['sequence_order'], unique=False)
    op.create_table('stage_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_notes', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('SHORTLISTED', 'APPEARED', 'SELECTED', 'REJECTED')", name='chk_assignment_status'),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['placement_stages.id'], ),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'student_user_id', name='uq_assignment_stage_student')
    )
    op.create_index(op.f('ix_stage_assignments_drive_id'), 'stage_assignments', ['drive_id'], unique=False)
    op.create_index(op.f('ix_stage_assignments_stage_id'), 'stage_assignments', ['stage_id'], unique=False)
    op.create_index(op.f('ix_stage_assignments_status'), 'stage_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_stage_assignments_student_user_id'), 'stage_assignments', ['student_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_assignments_student_user_id'), table_name='stage_assignments')
    op.drop_index(op.f('ix_stage_assignments_status'), table_name='stage_assignments')
    op.drop_index(op.f('ix_stage_assignments_stage_id'), table_name='stage_assignments')
    op.drop_index(op.f('ix_stage_assignments_drive_id'), table_name='stage_assignments')
    op.drop_table('stage_assignments')
    op.drop_index(op.f('ix_placement_stages_sequence_order'), table_name='placement_stages')
    op.drop_index(op.f('ix_placement_stages_drive_id'), table_name='placement_stages')
    op.drop_table('placement_stages')
    # ### end Alembic commands ###
